### ISSUE TITLE
update title ordering

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1019]
@mccalluc: Currently when the website concatenates the titles for the search results display, titles with the type "Label" show up first. I know this is based on the ordering of the mapping we have to clean up the data coming from the AMS, but is there a way, to move "Label" titles to the end of the title concatenation?

**Comment by mccalluc** [comment]
@sroosa: Could you change the order in https://github.com/WGBH/AAPB2/blob/master/config/vocab-maps/title-type-map.yml? It shouldn't go after the current last entry, because it's based on a left substring match, so the null-string captures everything, but any point above that would do. To find records which have labels: http://americanarchive.org/api.json?q=label_titles:*&fl=id,title&rows=100 ... note that most of these *only* have one label title, so changing the order won't change anything. After the config change is deployed, you'll need to reindex.

**Comment by sroosa** [comment]
@mccalluc: Will do! We're only worried about the ones that have labels and other titles, so the fact that it won't change most of them isn't a big deal. For the reindex after the config is changed, that can be a reindex of only the records that have labels, right? Not all of the records.

**Comment by mccalluc** [comment]
Yeah. Here's a script to get you the IDs of the ones that have a label and another title:
```ruby
require 'JSON'
require 'open-uri'

1.step do |i|
  docs = JSON.parse(URI.parse("http://americanarchive.org/api.json?q=label_titles:*&fl=id,title&rows=100&start=#{i*100}").read)['response']['docs']
  break if docs.empty?
  docs.each do |doc|
    puts [doc['id'], doc['title']].join("\t") if doc['title'] =~ /;/
  end
  sleep 0.1
end
```

(This is the sort of tool that I think more folks in the office should be comfortable making.)

**Comment by caseyedavis12** [comment]
@sroosa is this done?
