### ISSUE TITLE
Closed captioning still not appearing for records with captions

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1054]
I am sorry if this is duplicative of another issue but I could not find it. Closed caption files are still not appearing with the player for records that have an SRT file stored on AWS. I have tried in Chrome and Firefox and the issue is present in both.

**Comment by afred** [comment]
**Update:** VTT files work, but SRT files seem to be unsupported.

I need to catch up on where @mccalluc left off. I know that OV has a different way of showing the transcripts, where it serves SRT, but OV uses a different way of displaying it (i.e. it's displayed on the side to the right, with a few UI elements to help the  user along).

With AAPB, we're using native HTML5 `<track>` elements, and apparently, I'm seeing that SRT is still unsupported, while VTT seems to work in Chrome, FF, and Safari (from my minimal tests).

Additionally, it appears that our previous video player (videojs) also [only supports VTT](http://docs.videojs.com/docs/guides/tracks.html). If it was working before, i'm not sure how, and I don't remember seeing it. But I know there was a lot of discussion around it, so I might be missing something.

As it stands, i see 3 options:
  1. convert SRT to VTT. As i recall, these two formats are pretty similar, so conversion might not be too hairy. But we would probably want to convert everything before it gets put on S3.
  1. re-implement videojs player. The videojs player is popular and so it's fairly well supported, but it will make pages a little bit longer to load. Not sure how much.
  1. Implement the same thing that we did with OV. This will change the layout of the page for viewing videos, and take some time to adapt the code.

**Comment by mccalluc** [comment]
@afred: 
1. Yes, my sense is that VTT is the future, and that SRT is pretty similar, but it's never going to be supported by the browser built-in players. You might consider converting SRT to VTT on demand, and caching, rather than doing a batch job: you can handle the load, and if there are any quirks of the translation, fixing one line of code will be easier than having to rerun the entire process.
2. Using VideoJS isn't a bad choice... The page load time is negligible: The bigger trade-off I see is just the maintenance and complexity cost. JS video tools were more important when you needed Flash fallback.
3. I think I experimented with having a scrolling display of the closed captioning: Maybe it was on OV? The bigger problem is just how ugly CC is when you see more than one line at a time: Everything is all-caps, and it's littered with misspellings.

**Comment by afred** [comment]
@mccalluc thanks! Yeah, I see [some code that looks like you were trying something](https://github.com/WGBH/AAPB2/blob/master/app/views/catalog/_player.html.erb#L23-L31) out.

Good point about the advantage of on-the-fly conversion vs batch conversion of SRT to VTT. @caseyedavis12 Are we expecting to keep receiving SRT files over time?

**Comment by caseyedavis12** [comment]
@afred: For future digitization projects, if closed captioning exists, we will receive SRT files.

For our current IMLS project to create transcripts for the 40,000 hours and have the public fix the transcript through the Script Fixer game, we will be receiving phrase-level JSON. I can send an example if you would like to see one.

**Comment by caseyedavis12** [comment]
@afred: PS - our currently funded digitization project requires SRT files be delivered - this is already in the contract. But if in the future we want to require something different, we can require WEBVTT if that is preferred.

**Comment by afred** [comment]
@caseyedavis12 ok, thanks. I'll first look into doing a translation of SRT to VTT and see what that entails.
