### ISSUE TITLE
Add Spanish Language as Topic

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1056]
@sroosa: I think it would be a good idea to add "Spanish Language" as one of our PBCoreGenres. Could we apply this to all of the Spanish Radio Bilingue material? We may be getting another large Spanish language collection in the near future.

Once this is added to the records, we should remove one of the topics currently in the "Browse the Collection" list and replace it with "Spanish." Feel free to name the topic whatever you think is the best controlled term.

**Comment by sroosa** [comment]
@caseyedavis12 Okay! I think this is a good ideas, especially since we are not using instantiationLanguage. I will bulk add it to all of the spanish Radio Bilingue materials, and some of the other spanish language programs I already know of in other collections.

**Comment by sroosa** [comment]
Adding notes here about all of the steps that we'll need to take, so that we don't forget one and then need to reindex everything all over again. 
1. Add the genre term to the records in the AMS
2. Add the genre term to the genre vocab mapping for ingest into the AAPB
3. Add the genre term to the browse by topic section of the homepage
4. Reindex the records with the new genre term, to get new xml from AMS into AAPB
