### ISSUE TITLE
Video not playing on some devices

### ISSUE THREAD

**Issue by cmhosale** [WGBH/AAPB2#1073]
Yesterday we noticed that videos were not playing on older versions of Google Chrome, and not on Sadie's phone. Her phone is a Samsung Galaxy J3, running Andriod version 6.0.1. I checked that the videos should play, and they all looked good to me, so it was my assumption that the video player isn't working with some browsers.

**Comment by Muraszko** [comment]
[Possible reason from Stackoverflow?](http://stackoverflow.com/questions/32611368/android-marshmallow-cant-play-this-video-error)


"Videos with ODSM / SDSM codecs can bypass being deinterlaced, but it appears Android Marshmallow will not recognize ODSM / SDSM codecs and will require the videos to be deinterlaced. Previous OS versions will not play videos that haven't been deinterlaced normally, with the exception being the video file including ODSM or SDSM codecs.

I believe this is due to Quicktime support issues, and may need to be opened as a defect with Android Marshmallow, but may also be intended by Google."

Not the latest version of Android, but still supported by Google.

**Comment by sroosa** [comment]
Another video isn't playing for me in Chrome on my laptop, although the one I was having problems with before started playing.
Also noticed that the website is drawing 2 different players. Records that were up before have the old player (example: http://americanarchive.org/catalog/cpb-aacip_398-61djhhq3), and records that have been added recently have the new player (example: http://americanarchive.org/catalog/cpb-aacip_507-0000000k7v)

**Comment by Muraszko** [comment]
@sroosa I'm only getting the single, new player for each of those, not two different ones.  Weird.

I will say that the new records come from a vendor that's not the original one and are not 100% exactly the same specs, so that may be contributing to something going on here.  Or your computer is just giving you trouble.

**Comment by caseyedavis12** [comment]
@afred: I noticed that only the HTML 5 player is appearing for me today. Did we not switch over to the new player?

**Comment by afred** [comment]
@sroosa that smells like a caching issue. Try a hard refresh with `⌘ + R`. If you're still getting the old player, please let me know which browser, and which URL your trying.

**Comment by afred** [comment]
@caseyedavis12 The new player should be displaying for both http://americanarchive.org and http://demo.aapb.wgbh-mla.org. Please try what I suggested for @sroosa above.

Like @Muraszko mentioned on #1072, I don't have a lot of time to spend on AAPB stuff this week, but please feel free to document things we need to do in the next sprint leading up to the thing on Dec 7. Thanks!

**Comment by afred** [comment]
Closing since we don't have a specific device+browser for which the player isn't working.

If we discover a specific device+browser combo that's causing a problem, please open a new ticket with those specific details.

Also, the issue with VideoJS player not loading is addressed in #1077.
