### ISSUE TITLE
Add supplemental files to a record

### ISSUE THREAD

**Issue by cmhosale** [WGBH/AAPB2#1094]
For the Ken Burns project we need to provide users the option to download PDFs from Ken Burns Civil War AmercianArchive.org records. Can we build this functionality into the website?

**waiting on:**
  - [ ] Do we want to develop/design this so that it can be any kind of file, not just a pdf?
  - [ ] AMS needs to have a way to put links to PDF (or some other way of referencing a link to a PDF) in the pbcore metadata
  - [ ] Actual PDFs are uploaded to S3 somewhere.
  - [ ] AAPB team has decided how PDFs will appear to the user (open in a new tab, open in a popup window on the same page, something else?)
  - [ ] Design of how PDF assets will be displayed on the page.

**Done when:**
  - [ ] records with PDFs display as decided above
  - [ ] records with PDFs are re-indexed

**Comment by caseyedavis12** [comment]
Hey Charles, here are the URLs to the PDFs stored on S3:

https://s3.amazonaws.com/americanarchive.org/pdf-transcripts/burns-civilwar/CW_Interview_Bearrs.pdf

```https://s3.amazonaws.com/americanarchive.org/pdf-transcripts/burns-civilwar/CW_Interview_Fields.pdf

https://s3.amazonaws.com/americanarchive.org/pdf-transcripts/burns-civilwar/CW_Interview_Oates.pdf

https://s3.amazonaws.com/americanarchive.org/pdf-transcripts/burns-civilwar/CW_Interview_Safire.pdf

https://s3.amazonaws.com/americanarchive.org/pdf-transcripts/burns-civilwar/CW_Interview_Turner.pdf

https://s3.amazonaws.com/americanarchive.org/pdf-transcripts/burns-civilwar/CW_Interview_Warren.pdf

https://s3.amazonaws.com/americanarchive.org/pdf-transcripts/burns-civilwar/CW_Interview_Woodward.pdf```

There is no transcript for Symington.

**Comment by caseyedavis12** [comment]
@cmhosale closing.

**Comment by sroosa** [comment]
I think we should treat downloadable pdfs in one of two ways. 

One way could be similarly to how we treat thumbnails, where the website knows to look for them on S3. Because the majority of assets won't have downloadable pdf transcripts, though, we shouldn't have the website automatically check for all of the assets, but rather use an annotation field to indicate whether the website should call the pdf from S3. 

The other option I see is treating it more like we treat Outside URLs, where we put a link to the pdf in an annotation with annotation type "Downloadable Transcript" and have the website react specifically to the presence of the annotation. I think it would make sense for it to draw a button or something if a transcript exists, and when the user clicks the button the download just starts. 

The main difference between these two is whether or not we put the url to the transcript on S3 into the records, or if we just tell the website to look for a corresponding transcript on S3, which it could identify based on a specifically constructed filename. I see the ups and downs of both ways, so I think a developer should weigh in.

**Comment by jasoncorum** [comment]
Note to self: going with high because there is a design element which could take extra time.

**Comment by sroosa** [comment]
replaced with #1340
