### ISSUE TITLE
Episode title should appear before Episode Number title in Search Results

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1099]
Titles with title type "Episode" should appear before titles with title type "Episode Number" on AAPB search results pages.

**Comment by sroosa** [comment]
@caseyedavis12 I don't know that I agree with this. If it has ep # and episode title, I would like the title to display: Series; Ep #; Episode. 

Or are you only talking about in sorting the search results?

**Comment by caseyedavis12** [comment]
@sroosa: really? If Series; Ep #; Ep Title is standard practice, that is fine with me. It just looked a little strange seeing the Episode Number before the Episode Title.

**Comment by sroosa** [comment]
@caseyedavis12: I think it's standard practice, and i like it because if there is a series and you sort by title, then all of the episodes sort in episode number order. I think it might look a little weird because using semi colons and not having a # in front of the episode number are not standard practice, necessarily.

**Comment by caseyedavis12** [comment]
@sroosa should we be using periods instead of semi-colons to separate the titles in the title header?

**Comment by afred** [comment]
@caseyedavis12 @sroosa going to go ahead and close this. If you want to change the display in a different way (i.e use periods) then please open a new ticket. Thanks!
