### ISSUE TITLE
Install Pop Up Archive Kaldi speech-to-text software

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1106]
After our walk-through demo with Pop Up Archive on November 30, we would like to install the Pop Up Archive Kaldi Speech-to-text software and test it using Ken Burns The Civil War interviews.

https://github.com/popuparchive/american-archive-kaldi

All work to install this software should be charged to MLAPOPUP 785005.

**Done when:**
  - [x] server exists on AMS that can run the Kaldi software according to @cmhosale workflow.
  - [x] server is of an appropriate size
  - [x] server is re-buildable from our notes

**Comment by caseyedavis12** [comment]
@foo4thought: can you work with Charles to install the Pop Up Archive Kaldi software on the most powerful computer in the MLA as possible, so that @cmhosale can run tests of the software?

Please charge this time to MLAPOPUP 785005

Please if possible try to have this installed by the end of next week (Feb 24.)

**Comment by afred** [comment]
Note that because we use AWS, our "most powerful computer" is as powerful as we want it to be... for a cost of course.

**Comment by caseyedavis12** [comment]
@afred @foo4thought True. Would it be best to install this on Amazon instead of a local machine?

**Comment by afred** [comment]
**Pros** (to using AWS EC2 instnce for Kaldi - and other projects like this):
  * does not require procuring hardware
  * does not require any physical setup
  * can be accessed anywhere, provided you have the SSH key on your local machine. In this case, @cmhosale would likely just work from his current machine.

**Cons:**
  * does not support a desktop GUI (very easily anyway).
  * costs money. If you're talking about a beefy machine, it could get expensive if you leave it on (i.e. forget to turn it off when you're not using it, which can be easy to do).

**Conclusion:**
  * If we have the money for it
    _AND_ if we can make sure we turn it off when not in use
    _AND_ if Kaldi does not require you to install an app on your local machine, then I would recommend using AWS.
  * Conversely, if we don't have the money for it
   _OR_ if we don't want to risk racking up a bill because we forget to turn the machine off
   _OR_ if Kaldi cannot be operated completely through a combination of command line and/or web interace, then I would recommend using local hardware.
