### ISSUE TITLE
Chapterizing video

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1116]
We are interested in chapterizing video and audio that we feature in curated exhibits. Is there a way to do this using our current infrastructure (player and a file marking time codes in a github file), or do we need additional software for displaying the chapters?

See here for an example of a chapterized video: http://www.pbs.org/wgbh/americanexperience/films/penn/player/

**DONE WHEN**
- [ ] Video/audio that has Chapter annotation in AMS metadata record can be displayed within the player as chapters titles, and the user can click on a chapter title, and the player will progress to the start of that chapter.

**Comment by caseyedavis12** [comment]
This is a tool called OHMS developed by University of Kentucky that lets you chapterize oral histories: http://www.oralhistoryonline.org/start-using-ohms/

**Comment by jasoncorum** [comment]
@caseyedavis12 @afred It does look like videojs supports chapters using the text tracks:
http://docs.videojs.com/docs/guides/tracks.html

I think I'll do a quick and dirty implementation just to get a sense of what it would look like and post a screenshot here.

**Comment by jasoncorum** [comment]
@caseyedavis12 @afred Here's what video-js chapters look like out of the box. As background, it uses a WebVTT file similar to captions, so it might make sense to add a pbcoreAnnotation for "Chapters URL" or something similar for videos we'd like to chapterize.
![screen shot 2016-12-12 at 11 10 11 am](https://cloud.githubusercontent.com/assets/3814190/21106561/8c2b3cc0-c05c-11e6-9607-393d4377f52e.png)

**Comment by caseyedavis12** [comment]
@jasoncorum this looks great to me!

cc @sroosa, this is something we will need include when preparing the newsmagazine exhibit which will launch in June.

**Comment by sroosa** [comment]
@jasoncorum Cool! Can you name chapters different from "chapter 1." Like could I put in the segment titles and have them show up in the menu in the player?

**Comment by jasoncorum** [comment]
@sroosa - No, I just threw those chapter names in there.

**Comment by jasoncorum** [comment]
@sroosa @caseyedavis12 @afred - Attached is an example of a webvtt chapter file (saved as a .txt file instead of .vtt so I could attach it here). The 3rd line of each chunk is what will display as the chapter title.

Are these already annotated in AMS records? If so, how and do you have an example? Thanks!
[example_1.txt](https://github.com/WGBH/AAPB2/files/844908/example_1.txt)

**Comment by jasoncorum** [comment]
Notes for self for implementation:

1. Something is weird with VideoJS and simply adding a chapters track doesn't prompt it to display. We need to remove the "vjs-hidden" class from the chapters div to get it to display.
2. Here is the format for the chapters track in the view (since it is not well documented):

<track kind="chapters" src="/assets/example_1.vtt" srclang="en" label="Chapters" />

**Comment by sroosa** [comment]
@jasoncorum: would it work if we made .vtt chapter files, named them the same way we name the thumbnails, and threw them up on s3? I don't think we can store this metadata in the pbcore in the AMS. Would you want the pbcore to have a marker indicating to look for a .vtt file? or would you just do it the way you are currently doing it for thumbnails and transcripts?

**Comment by jasoncorum** [comment]
@sroosa - Now that I know the code better, I think we'd do it exactly in the way you describe (and how we just did captions). We'd just need the files to place on S3. On ingest, we can check for a file on s3 and then use it if it is available.

**Comment by sroosa** [comment]
@jasoncorum Okay! I'll work on getting a few tests files together and up on S3.

**Comment by jasoncorum** [comment]
@sroosa - I meant the PUA transcripts, not captions. Anyways, cool! Let me know when they're ready!

**Comment by sroosa** [comment]
@jasoncorum I added one file to S3 so far. I made a new folder called chapters, and it's in there. I'll add a few more today/tomorrow.

**Comment by jasoncorum** [comment]
Note for self: Don't think we need the annotation and we can just build the URL in the application based on the GUID.

**Comment by jasoncorum** [comment]
@sroosa - I bumped up the width and font-size of "CHAPTERS". I didn't increase space between chapters because I don't think it necessarily needs it after the changes we've made. Additional thoughts?

![screen shot 2017-06-30 at 10 01 23 am](https://user-images.githubusercontent.com/3814190/27739124-88607daa-5d7b-11e7-9ccf-5a56b3b7186e.png)

**Comment by sroosa** [comment]
@jasoncorum So much better! I love it!

**Comment by caseyedavis12** [comment]
@jasoncorum - ditto looks amazing.
