### ISSUE TITLE
Genre facet is too long

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#117]
@sroosa : what do we want to do with the genre facet?
- One possibility: just list the first `n` in the UI?
- and/or vocab mapping?

**Comment by sroosa** [comment]
At this point I think the index of values in the genre field is too crazy to map. I'd like to go with just listing the first 10 or 20. @caseyedavis12 do you have an opinion?

**Comment by caseyedavis12** [comment]
Hi everyone — apologies, but do you mean the number of values in the facet is too long to display on the page? If we just list the first 10 or 20, will the user never be able to browse via the facet menu the records that are cataloged with the other values?

**Comment by sroosa** [comment]
If they narrow the search results further, then the genre facets will adjust, and only genres used in records that fit the search criteria will appear. But yes, it will not show the other genre values. 
At this point, since most of the genre data is kinda all over the place, I don't think that would be a bad thing, really. Once more records use our controlled vocabulary, then it might be a good idea to revisit then.

**Comment by caseyedavis12** [comment]
That works. Our controlled vocabulary is more than 20 values, too. But hopefully by the time we revisit, we will be able to break that facet into two separate facets (topic and format).

**Comment by sroosa** [comment]
That was my idea too!

@mccalluc I think we can go ahead an limit the genre facet to just list the first 20 terms in the UI. Thanks!

**Comment by mccalluc** [comment]
fixed in #157
