### ISSUE TITLE
16x9 encoded proxies appear squished in Firefox  

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1171]
**Charge work to Overhead 156840**

16x9 encoded proxies appear fine in Google Chrome and Safari. That is, they display at 16x9 with letterboxing on top and bottom. In firefox, the 16x9 videos appear squished in a 4x3 player with no letterboxing. This issue may also be present in Internet Explorer but I have not checked.

**Done when**
- [ ] 16x9 encoded proxies do not appear squished in FireFox
- [ ] **OR** if it's a problem with Firefox, add a message for Firefox users to try another browser? <== @caseyedavis12 is that ok?

**Comment by caseyedavis12** [comment]
Charge work to Overhead 156840

**Comment by jasoncorum** [comment]
@caseyedavis12 could you add a link for testing and review? Thanks!

**Comment by caseyedavis12** [comment]
@jasoncorum: Here you go! http://americanarchive.org/catalog/cpb-aacip_504-3t9d50gd44

[http://americanarchive.org.s3.amazonaws.com/thumbnail/cpb-aacip_504-3t9d50gd44.jpg]<http://americanarchive.org/catalog/cpb-aacip_504-3t9d50gd44>

American Masters; 1603; Juilliard<http://americanarchive.org/catalog/cpb-aacip_504-3t9d50gd44>
americanarchive.org
Interview: Audra McDonald

**Comment by cmhosale** [comment]
Interestingly, a video that was natively 16x9 is displaying correctly in firefox. I do not know if that is true of all native 16x9 files. The files that we originally noted were not displaying correctly were reencoded by me to display as 16x9. They still have a 4:3 pixel size, but have a 16x9 Display Aspect Ratio. It seems that the player in firefox might not be looking at the display aspect ratio?

Attached please find mediainfo for a native 16x9 file that is displaying correctly (http://americanarchive.org/catalog/cpb-aacip_504-g44hm5362c) and a 4:3 file reencoded to be 16x9 that is not displaying correctly (http://americanarchive.org/catalog/cpb-aacip_504-9s1kh0fh8p).

[4x3reencoded.txt](https://github.com/WGBH/AAPB2/files/777286/4x3reencoded.txt)
[16x9native.txt](https://github.com/WGBH/AAPB2/files/777285/16x9native.txt)

**Comment by jasoncorum** [comment]
Begin troubleshooting by using a straight-up HTML 5 video player and see how it renders in Firefox to determine if issue is part of VideoJS.

**Comment by jasoncorum** [comment]
Notes: Video wasn’t displaying correctly in vanilla HTML5 player, either.

Found the following link on a quick Google search about encoding anamorphic video:
 
https://video.stackexchange.com/questions/20871/how-do-i-convert-anamorphic-hdv-video-to-normal-h-264-video-with-ffmpeg-how-to/20872
 
Here’s the output file I received after running the command from the above link:
 
https://s3.amazonaws.com/americanarchive.org/test/cpb-aacip-504-3t9d50gd44_16x9.h264-2.mp4

This video displayed correctly locally in Firefox.  Sent to @cmhosale for review since he knows video encoding a lot better than me.

**Comment by jasoncorum** [comment]
from @cmhosale: 

The follow up on this is that we decided to transcode the anamorphic videos to have a 16:9 pixel aspect ratio. We previously had just added a flag to the container which set the display aspect ratio at 16:9. This of course was too elegant to actually work, and the flag was ignored in our player in Firefox. In the future we should specify that anamorphic video proxies be struck with a 16:9 pixel aspect ratio (I'm actually going to double check this for latter NewsHour recordings 😞 ).

The ffmpeg command I used to make the new proxies was:

`ffmpeg -i INPUTGOESHERE -vf scale=480:270 -c:v libx264 -b:v 711k -pix_fmt yuv420p OUTPUTGOESHERE.mp4`

These proxies are 16:9 and are pretty tiny, but retain our higher bitrate. I believe that there was no reason to go higher resolution than these because we didn't have the masters, and anything higher would be dead data. For collections where we have the master, we might want to go higher dependent on the original format.
