### ISSUE TITLE
Searching the AAPB site returns '500' error

### ISSUE THREAD

**Issue by rfraimow** [WGBH/AAPB2#1218]
Error consistent across two different browsers and on two different computers

**Comment by jasoncorum** [comment]
@afred - @Muraszko-wgbh and I ran a swap because the issue looks like a weird one.  The issue is now on the demo server.

When I ps for jetty, I'm not getting any processes, but when I try to start jetty I get the following message:

"Server is already running with PID 0"

I followed that up with killing process 0, but still get the same message when attempting to start jetty. Have you seen anything like this before?

**Comment by afred** [comment]
this seems to have been due to stale PID files. I deleted them from `shared/tmp/pids/` and restarted jetty and seems to be working now. Closing
