### ISSUE TITLE
Recent blog post not appearing on website homepage

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1258]
Done when

- [ ] title of most recent blog post appears on the website homepage

![screen shot 2017-05-05 at 4 56 36 pm](https://cloud.githubusercontent.com/assets/5992135/25764036/fcb480b4-31b3-11e7-81a4-0333657e865d.png)

**Comment by caseyedavis12** [comment]
It's appearing now.

**Comment by caseyedavis12** [comment]
This issue is happening again.

**Comment by jasoncorum** [comment]
@caseyedavis12 - this worked itself out. what happens here is that if the site doesn't get a response from wordpress when it checks for new blog posts it doesn't display anything. it then checks for another response in an hour and then repopulates. since it keeps happening, we should probably come up with something better. i created a new ticket here: https://github.com/WGBH/AAPB2/issues/1300.
