### ISSUE TITLE
Get a subdomain name

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#130]
Hopefully we can do a subdomain? Where does this get registered?

**Comment by caseyedavis12** [comment]
I will talk to Donna Taub about getting a subdomain. It is not difficult. Can do this week.

**Comment by mccalluc** [comment]
Awesome. The blog is now at blog.americanarchive.org. Wordpress is redirecting from the old to the new.

@caseyedavis12 :
- Maybe some content that's now on the blog will be moving to the main site (mission statement, etc.)?
   - Will we remove the similar content from the blog at launch?
   - Would there need to be redirects from the blog to the site?
- And conversely, is it acceptable for links like http://americanarchive.org/participating-orgs/ to 404 after launch?

Setting up redirects isn't hard, but if it's not necessary I don't want to invent work, either. Mostly I want to minimize surprises at launch. Thanks!

**Comment by caseyedavis12** [comment]
Hi Chuck,

Yes, some content that's now on the blog will be moving to the main site (mission statement, etc.). Sadie has already created a document that identifies which pages will be moved to the new site. When the pages are moved to the new site, we will delete those pages from the blog. It would be awesome if we could keep the URLs the same for those pages when possible, so that we don't have any 404 errors.

Best,
Casey

**Comment by mccalluc** [comment]
Thanks! I've filed #133 to port the static pages, and #134 to remove them from the blog, post-launch. closing.
