### ISSUE TITLE
9 items listed at bottom of exhibit section

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1383]
@jasoncorum: On all exhibits, we currently list 9 random items that are hyperlinked within the text of that narrative. If there are more than 9, it says "Show all items"

It made sense for our early exhibits but not anymore. This makes no sense at all to users especially for the watergate exhibit. For example this is what shows up on some of the watergate exhibits pages. Can we do something about this?

![screen shot 2017-10-27 at 1 06 56 pm 2](https://user-images.githubusercontent.com/5992135/32116229-c93b9c16-bb17-11e7-8556-18d748c72a44.png)
![screen shot 2017-10-27 at 1 06 58 pm](https://user-images.githubusercontent.com/5992135/32116230-c945bfc0-bb17-11e7-800a-ec9a49b710f0.png)
![screen shot 2017-10-27 at 1 07 08 pm](https://user-images.githubusercontent.com/5992135/32116231-c94e315a-bb17-11e7-9837-da9a77e219c7.png)

**Comment by caseyedavis12** [comment]
![screen shot 2017-10-27 at 1 09 15 pm](https://user-images.githubusercontent.com/5992135/32116303-13fe793a-bb18-11e7-9d6e-8cfeae91c774.png)

**Comment by caseyedavis12** [comment]
![screen shot 2017-10-27 at 1 10 37 pm](https://user-images.githubusercontent.com/5992135/32116342-3dc2285c-bb18-11e7-982a-b032839c17fd.png)

**Comment by jasoncorum** [comment]
@caseyedavis12 - so is the desired functionality that these 9 items never appears for any exhibit?

**Comment by caseyedavis12** [comment]
@jasoncorum:

We eventually plan to redesign the look of the exhibits, but for now, could you just change the text that displays with the thumbnail to show the concatenated title rather than the hyperlinked text from that section?


Best,

Casey

**Comment by caseyedavis12** [comment]
@jasoncorum: And it might be clearer to users if we added a header above the 9 items that says "Items featured in this section:"



________________________________

**Comment by jasoncorum** [comment]
Just discussed with @caseyedavis12 and @sroosa. In order to get Phydo work in during this sprint, we're going to just hide the "items" for now rather than update to use the actual record title. This update won't play very nice with our development and testing setups due to the fact that we don't have the entire catalog indexed in those instances.

**Comment by jasoncorum** [comment]
@caseyedavis12 - how does this look? it essentially works the same across exhibits. it shows the top page title for the exhibit and then links to a search for all records within the exhibit.

![screen shot 2017-10-30 at 3 20 25 pm](https://user-images.githubusercontent.com/3814190/32190998-f3540a04-bd85-11e7-8a37-9e61a3d2167f.png)

**Comment by jasoncorum** [comment]
@caseyedavis12 - thanks for the clarification. updated per the conversation so that we continue to use the existing functionality wherein each page within an exhibit links to a results page with all the items included. See below.

Bad news is that the "Next" links are hardcoded in to the main HTML for each page, so won't have time to put the "Show All Items" above them. It'd require some new functionality and then editing the main HTML for every exhibit page.

![screen shot 2017-10-30 at 3 43 54 pm](https://user-images.githubusercontent.com/3814190/32192055-701ab2a6-bd89-11e7-83e6-833cf11d30a2.png)

**Comment by jasoncorum** [comment]
Reviewed in person.
