### ISSUE TITLE
Watergate captions appear when you click "show all items"

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1401]
The Watergate image captions appear when  you click "show all items" on the homepage and on some section pages. Can we remove the appearance of the "Summary" when you click "Show all items"

**Comment by jasoncorum** [comment]
@caseyedavis12 - chatted with @sroosa and thought that rather than just dropping the text and leaving the exhibit title linked at the top, we could move that up in to a breadcrumb like we're using for special collections. here's a screenshot. thoughts?

![screen shot 2017-11-02 at 3 08 44 pm](https://user-images.githubusercontent.com/3814190/32345292-2038a212-bfe0-11e7-8891-3440ab1fc920.png)

**Comment by caseyedavis12** [comment]
@jasoncorum: Freaking amazing!!!

@sroosa
