### ISSUE TITLE
parse timecode passed in url 

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1518]
adding "#at_[number]_s" playback works with the transcript clicks and it looks like the primary issue is that we just need to parse that on page load, as well. that would be an easy fix but chrome has updated how they handle autoplay, so that would complicate the fix a little bit. https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by jasoncorum** [comment]
The issue here was with new browser policies about autoplay. Essentially we were using autoplay to push the user past the poster image and to pause the video at the timestamp. This JS errors with the new browser update. Removing the autoplay and pause fixes the issue, but now the user just gets the poster image before hitting play. Want to review with @sroosa to see how much time we want to use in trying to replicate the old functionality vs. rolling with this fix.
