### ISSUE TITLE
put state abbreviations on orgs facet

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#212]
@caseyedavis12 : ok to put them first, so the list of stations will be sorted geographically? Or whatever you'd prefer.
> (MA) WGBH
> (NY) WNYC

**Comment by caseyedavis12** [comment]
I say let's put the abbreviation last since the primary function of the Organization facet is to allow for filtering by Organization, so the Organizations should be in alphabetical order followed by the abbreviation of the state. By October, I hope to have implemented geoblacklight which allows for a mapping of the content by state, so that will be a better way of browsing by location, but for now, adding the state abbreviation after the organization name is good.

**Comment by caseyedavis12** [comment]
I say let's put the abbreviation last since the primary function of the Organization facet is to allow for filtering by Organization, so the Organizations should be in alphabetical order followed by the abbreviation of the state. By October, I hope to have implemented geoblacklight which allows for a mapping of the content by state, so that will be a better way of browsing by location, but for now, adding the state abbreviation after the organization name is good.

**Comment by mccalluc** [comment]
@caseyedavis12 :
> WGBH (MA)
> WNYC (NY)

That look good? Just want to make sure then parenthesis and everything are what you want.

Looking ahead, I'd encourage us not to set goals like "implement package X":
- Most packages have a range of functionality, and we risk scope creep ("Well let's turn on feature Y while we're here.") and losing track the original goal.
- Concerning geoblacklight in particular, it's very useful when each record might have a different location, but when there are only a hundred different points of interest, recording lat-longs on every single record is hugely redundant, and actually not that useful: Having a few thousand pushpins at the same point isn't helping anyone.

**Comment by caseyedavis12** [comment]
The abbreviation after the station name looks good.

**Comment by caseyedavis12** [comment]
Off topic but in regard to mapping functionality, I meant to say "like geoblacklight." Not sure what the DPLA uses but here is an example of an organization with millions of records using a map functionality: http://dp.la/map

**Comment by mccalluc** [comment]
- tweak `to_solr`'s organization facet to add state abbr.
- add state abbr accessor to org objects.
- hash lookup based on statename. (also validate states at rails startup.)
