### ISSUE TITLE
Cataloging: clean up multiple Ci-IDs

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#253]
and once they are fixed, make `PBCore#ci_id` require at most one.

**Comment by mccalluc** [comment]
@foo4thought : I should have written more when I filed this, but I don't remember now what this is about: Is there a clean up that needs to be made in the AMS?

**Comment by foo4thought** [comment]
No cleanup is necessary, AFAIK



-- kevin carter
-- programmer analyst
-- wgbh educational foundation
-- 1 guest street
-- boston, ma, usa, 02135
-- 6173005923 v/vm/fax
-- www.wgbh.org

-- WGBH:  pioneering public education since 1951 with content and
technology to enlighten and enable.
________________________________

**Comment by mccalluc** [comment]
We will actually support multiple Ci Assets per record. See #457. Closing.
