### ISSUE TITLE
Reuploading the 450 files that failed upload to Ci

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#342]
Later in April or May, @Muraszko will work on reuploading approximately 450 files that failed uploading to Ci. He will deliver Ci IDs to Kevin. Kevin will insert. Chuck will download and reingest those records.

**Comment by mccalluc** [comment]
@Muraszko : did this happen?

**Comment by mccalluc** [comment]
@Muraszko / @foo4thought : pinging again. Did this happen?

**Comment by Muraszko** [comment]
@mccalluc Sorry, didn't see that.  Yes, I re-ingested all the failed to upload files.  They were mostly the larger files over 750MB in size.

**Comment by mccalluc** [comment]
Do either of you have an ID or two we could check to make sure these came through? I have no memory of this, so I'd like to be a little more confident before closing.

**Comment by mccalluc** [comment]
Got the list from Mike. Thanks! A few:
- http://americanarchive.org/catalog/cpb-aacip_260-784j17bx : 500 from redirect
- http://americanarchive.org/catalog/cpb-aacip_398-741rnj7q : 500 from redirect
- http://americanarchive.org/catalog/cpb-aacip_151-7h1dj5909s : no player, period

Plan: Update just the IDs from Mike's docs and look again.

**Comment by mccalluc** [comment]
erg... We still have problems. Maybe there are some that work, but none that I've checked are working: Load http://americanarchive.org/catalog/cpb-aacip_260-784j17bx.pbcore:
```xml
<pbcoreIdentifier source="Sony Ci">14b572b03ce64772b4d825e7626892f0</pbcoreIdentifier>
```
First tried the command line script:
```
$ bundle exec sony-ci-api --down 14b572b03ce64772b4d825e7626892f0
# no output. (Filed bug to make this more informative.)
```
Then tried looking at it from the Ci web app: https://workspace.cimediacloud.com/workspace/051303c1c1d24da7988128e6d2f56aa9#/folder?assets=14b572b03ce64772b4d825e7626892f0
```
This file is still being uploaded. Patience is a virtue.
```
@Muraszko : Did you get some positive indication that this had worked? Are you hitting the big file upload problem? I'm going to assign this to you since I think we do need to start over from the top.

**Comment by Muraszko** [comment]
@mccalluc See email.

**Comment by mccalluc** [comment]
My mistake: I assumed the data on the AAPB site was accurate.
```
$ grep 260-784 Re_Upload/*
Re_Upload/AA1675L5_Ci_Log_RE.csv:2015-04-29 06:13:25 -0400	cpb-aacip-260-784j17bx.h264.mp4	616525f67e304cad8abbc2aa6ff3aaff	...
```
and that Ci ID does work: https://workspace.cimediacloud.com/workspace/051303c1c1d24da7988128e6d2f56aa9#/folder?assets=616525f67e304cad8abbc2aa6ff3aaff
```
Has it been updated in the AMS? https://ams.americanarchive.org/xml/pbcore/key/b5f3288f3c6b6274c3455ec16a2bb67a/guid/260-784j17bx
```
<pbcoreIdentifier source="Sony Ci">14b572b03ce64772b4d825e7626892f0</pbcoreIdentifier>
```

No: on this one at least, the data in the AMS does not reflect the latest upload Mike did. So, @foo4thought, on your plate to ingest all of these into AMS, since that seems to be the problem. Reassigned.

**Comment by foo4thought** [comment]
The GUID and "old" sony id provided appears in only one place in my collection of CSV data, and that is *not* in the subset of 350 items designated "Re_Upload"   If 450 items were involved, then at least 100 were not reprocessed.  Where would be that list?

**Comment by mccalluc** [comment]
@Muraszko : I think Kevin's question is for you?

**Comment by Muraszko** [comment]
@foo4thought Just emailed you again the list of CSV files to extract new Ci IDs from.

**Comment by foo4thought** [comment]
I'm pretty sure I already processed those items

Will verify



-- kevin carter
-- programmer analyst
-- wgbh educational foundation
-- 1 guest street
-- boston, ma, usa, 02135
-- 6173005923 v/vm/fax
-- www.wgbh.org

-- WGBH:  pioneering public education since 1951 with content and
technology to enlighten and enable.

________________________________________

**Comment by mccalluc** [comment]
@foo4thought / @Muraszko : Where does this stand? I don't have a good handle on the issues, but the instance I was checking on June 9 still does not work, I think:

>
Has it been updated in the AMS? https://ams.americanarchive.org/xml/pbcore/key/b5f3288f3c6b6274c3455ec16a2bb67a/guid/260-784j17bx
>
`<pbcoreIdentifier source="Sony Ci">14b572b03ce64772b4d825e7626892f0</pbcoreIdentifier>`

That is still the case.

**Comment by mccalluc** [comment]
@foo4thought : Is this another side of #460? If so, feel free to close; if not, what do we do to get there?

**Comment by foo4thought** [comment]
Almost certainly so; we'll know shortly.

-- kevin carter

-- programmer analyst

-- wgbh educational foundation

-- 1 guest street

-- boston, ma, usa, 02135

-- 6173005923 v/vm/fax

-- www.wgbh.org<http://www.wgbh.org>

-- WGBH:  pioneering public education since 1951 with content and

technology to enlighten and enable.

________________________________

**Comment by foo4thought** [comment]
261 Sony identifiers have been inserted to the AMS and affected assets have been reindexed; any/all existing assignments of Sony identifiers to these assets were removed. This is the balance of work started mid-March and resumed at the end of April.  These items weren't done at that time because I overlooked the need to perform a secondary process to handle items affected by Zend/Google library bug (aka "missing items from Crawford").
