### ISSUE TITLE
License

### ISSUE THREAD

**Issue by edsu** [WGBH/AAPB2#353]
You all deserve a lot of credit for working out in the open on GitHub. Have you thought about adding a license to the code?

**Comment by caseyedavis12** [comment]
Thank you, Ed! We're working on this...

**Comment by mccalluc** [comment]
@caseyedavis12 : any word from the lawyers?

**Comment by caseyedavis12** [comment]
It's on their to-do list for AAPB. No definitive answer yet.

**Comment by mccalluc** [comment]
@caseyedavis12 : status?

**Comment by caseyedavis12** [comment]
Legal Counsel still working on this. It is 3rd in priority on their list of tasks to accomplish for AAPB.

**Comment by mccalluc** [comment]
I hope it is clear that they are they are not writing any new language. Someone just needs to make a choice between MIT/Apache/GPL. Ideally, this would just be an organization-wide policy. It does not need to be revisited for every project.

**Comment by caseyedavis12** [comment]
Yes, it is clear. We have a new legal counsel who recently joined the Project. She has several other items on her plate for AAPB right now, and we have put the license as lower priority since others are time-sensitive, including the ORR Rules of Use.

It actually does need to be revisited for every project because there are always different licenses to the underlying copyrightable components of the code, which impact the license that we can choose for our code.

**Comment by caseyedavis12** [comment]
To add to the License.md or License.txt page:

"Copyright (c) WGBH Educational Foundation

This project is licensed under the terms of the Apache License Version 2.0: http://www.apache.org/licenses/LICENSE-2.0.txt

The project consists of copyrighted components that are subject to the terms of licenses, including:

Ruby on Rails — MIT License (http://rubyonrails.org/)
Solr — Apache License Version 2.0 (http://lucene.apache.org/solr/)
Blacklight -- Apache License Version 2.0 (https://github.com/projectblacklight/blacklight)"
