### ISSUE TITLE
Conducting a search using quotes

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#400]
When a user conducts a search using quotes around the search terms, only records containing that exact phrase should be retrieved. Example: search for "in search" on the website.

**Comment by mccalluc** [comment]
Blacklight already gives us phrase searching out of the box:

http://americanarchive.org/catalog?q="ice+fishing" -> 215
vs http://americanarchive.org/catalog?q=ice+fishing -> 466

http://americanarchive.org/catalog?q="horse+recipe" -> 0
vs http://americanarchive.org/catalog?q=horse+recipe -> 24

Your example, "in search" is different because "in" is a stopword: it is simply not indexed. I am very, very reluctant to reindex without stopwords. @caseyedavis12, ok to close?
