### ISSUE TITLE
Search for "cooking"

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#402]
When a user conducts a search for cooking, records about "Bob Cook" are retrieved. The word "cooking" does not appear in the record. Why is this record retrieved?

**Comment by sroosa** [comment]
Because the search does fuzzy searching, so that a user doesn't have to type the word exactly to get the relevant results. It clearly has it's draw backs as well as it's benefits.

**Comment by caseyedavis12** [comment]
If a user conducts a search for "cooking" with quotes, the retrieved results should only include records that contain the exact word "cooking." If a user does not use quotes, we could keep the current functionality for the broader retrieved results.

**Comment by mccalluc** [comment]
I don't think this is going in the right direction.
- I need to go to the [fourth results page](http://americanarchive.org/catalog?page=4&q=cooking) before I get something that isn't about food-cooking. Conversely, there is a "cook-off" result, and I wouldn't want to lose it.
- We already want to use "..." for phrase searching: overloading it with exact string searching will make it even trickier to implement.
- Adding support for exact string searches will probably double the size of our index, or more: instead of recording cross references for stemmed forms, it will need to keep track of every single unique string.

On the other hand,
- "..." for exact search is something google supports. Compare ["cookings"](https://www.google.com/search?q=%22cookings%22) with [cookings](https://www.google.com/search?q=cookings)

so it's not impossible, but it seems really high-cost/low-benefit to me.

**Comment by mccalluc** [comment]
Not hearing any counter arguments, I'll close this. If there are other arguments out there, we can talk.
