### ISSUE TITLE
Re-focus intern work on Online Reading Room items

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#404]
Karen and Alan want to refocus intern efforts on materials that will be available in the Online Reading Room

**Comment by sroosa** [comment]
I can do this, but it goes exactly against everything Karen originally asked for in terms of cataloging. She wanted to leave the stuff that can go in the ORR alone, so that if we get the grant for seniors and other crowdsource cataloging, they actually have something available to catalog that hasn't been cataloged by interns already. Just checking that this is a shift in priority we're 100% behind.

**Comment by caseyedavis12** [comment]
We just discussed this and both of them agree that focusing on ORR items is best.
