### ISSUE TITLE
"missing value" records from WGBH

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#472]
For example: http://americanarchive.org/catalog/cpb-aacip_15-ks6j09wb2h
>
missing value
Description
    missing value
Media type
    other

This is of no use to anyone. It looks like there are 891 of these: http://americanarchive.org/catalog?q=%22missing+value%22 

Let's either
- Fix these records and reingest
- Or delete in the AMS and AAPB

**Comment by mccalluc** [comment]
@sroosa : Data quality issue: can you prioritize and invesitgate?

**Comment by sroosa** [comment]
@mccalluc: yes. I'll investigate now and propose a solution, which I assume will be some form of cataloging work.

**Comment by sroosa** [comment]
Since i'm handling this with cataloging work in the AMS, rather than through website code, i'm closing this here.

**Comment by mccalluc** [comment]
@sroosa: I'm going to reopen this, and we can close it was the cataloging work is done and its been reingested. Otherwise, if someone notices the problem again and searches for it, they might think something new has cropped up, and it's not just the same old problem.

Is this ok?

**Comment by sroosa** [comment]
@mccalluc That makes perfect sense. I'll close only when the issues is resolved in the AMS.

**Comment by sroosa** [comment]
@mccalluc I handles the "missing value" descriptions, by just having Kevin deleted them, since they serve no purpose. But I cannot handle the "missing value" titles the same way, since we need to have something as a title for the website. And we don't currently have enough time or man power to go in and figure out what the titles should be and add them. Do you have any suggestions on what to do about the titles, either in the AMS, or when we ingest/display the data on the website?

**Comment by mccalluc** [comment]
When I opened this, for all I knew, there might have been useful data that was being dropped by mistake... but that's not the case. We're saying all we have to say, and the records have some data (cryptic IDs), so I'm happy with the status quo. Closing.
