### ISSUE TITLE
Discuss: Metadata redundancy in descriptions

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#482]
For a lot of WGBH digital assets, there are two of the same descriptions appearing in the web application. Here is an example: http://americanarchive.org/catalog/cpb-aacip_15-rj48p5vm8b.

This is a problem with the metadata. In the AMS, I see that one description type = "Summary3" and another description type = "Episode Description."

Does this need to be cleaned up in the AMS before it can appear cleaned up in the web application? 
@sroosa  is working on creating descriptions for "Series," so this would be a higher level description than an episode description. But it is preferred that each unique description only appear once in the metadata record.

**Comment by mccalluc** [comment]
Looking at a couple examples:

http://americanarchive.org/catalog/cpb-aacip_384-1615dxnn.pbcore
```xml
...
<pbcoreTitle titleType="Clip">Kansas City Week in Review #233, 5/27/94; Kansas City Week in Review #234, 6/3/94</pbcoreTitle>
<pbcoreDescription>Kansas City Week in Review #233, 5/27/94; Kansas City Week in Review #234, 6/3/94</pbcoreDescription>
...
<instantiationIdentifier source="KCPT7123">Kansas City Week in Review #233, 5/27/94; Kansas City Week in Review #234, 6/3/94</instantiationIdentifier>
...
```
http://americanarchive.org/catalog/cpb-aacip_15-rj48p5vm8b.pbcore
```xml
...
<pbcoreTitle titleType="Program">After Copenhagen: Real Solutions for Global Climate Change</pbcoreTitle>
...
<pbcoreTitle titleType="Uncataloged">After Copenhagen: Real Solutions for Global Climate Change</pbcoreTitle>
...
<pbcoreDescription descriptionType="Episode">The December 2009 Copenhagen talks on global climate change ...</pbcoreDescription>
<pbcoreDescription descriptionType="Description">The December 2009 Copenhagen talks on global climate change ...</pbcoreDescription>
```

- If we did this, I would probably do it on ingest. Because it crosses many fields, it's not as amenable to fix-at-view-time, though that's still possible.
- If I were to fix exactly the kinds of problems in the examples, is that enough, or do we need something more general? (I hope not.)
- What's the desired end goal? Proposal:
  - First example: If a given value occurs across multiple elements, including title, keep it only in title.
  - Second example: If a given element value is repeated, keep only the first instance. (Elements are sorted by vocab maps.)

Go ahead with this?

**Comment by afred** [comment]
re-opened per discussion on 7/7/15

**Comment by mccalluc** [comment]
More generally, any of the vocab-mapped fields will keep only one instance of a repeated value. Prefer the higher priority one.

As I'm thinking about this now, it would probably be best at ingest-time, but not sure that's good enough.

**Comment by sroosa** [comment]
I think it would be best at ingest-time. @mccalluc are you worried about introducing more redundancies after ingest-time, or do you just think we shoudl figure out way to handle this before export from AMS?

**Comment by mccalluc** [comment]
Ingest-time works for me: the downside is just that you need to reingest to see the difference. (I'm pretty comfortable putting any number of ad-hoc tweak in the ingest cleaning: Trying to do the same thing at render time will become a maintenance headache, I'm afraid.) Thanks.
