### ISSUE TITLE
Show all titles concatenated in search results

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#508]
- On search results, show all the titles on a single line, joined with commas.
- Since it's redundant, don't show the titles on search results broken out by type.
- No change to the details page.

**Comment by caseyedavis12** [comment]
@mccalluc: Is there any reason why it is preferred to separate titles by commas instead of formatted like "Series: Program (Episode #)" or "Program (Episode #)"  when this information exists? If this information does not exist, then "Program" or "Promo." If not one of our 7 title types, then list it in the search results below the title that is presented as the header.

**Comment by caseyedavis12** [comment]
@mccalluc: actually, disregard the last question. I started thinking of the scenarios and see how it would be time consuming to plan for all possibilities. Separating by commas sounds fine, but if we are separating by commas, I agree with Drew that it is helpful to see the titles broken out with labels in the search results.

**Comment by mccalluc** [comment]
@caseyedavis12 : Is it most granular to least, or the other way around? And commas are the punctuation? ie
- `Nova, 123, Secret Weapons of the Dinosaurs, Claw Extender Footage` or
- `Claw Extender Footage, Secret Weapons of the Dinosaurs, 123, Nova` or
- something else?

**Comment by caseyedavis12** [comment]
@mccalluc: can you hold off on this ticket until tomorrow? I am awaiting a little more clarification from Alan on this suggestion.

**Comment by afred** [comment]
Gah!, sorry @caseyedavis12, i didn't read through all these comments until just after merging the PR.

Are we good to go with this? The merged PR appears to use commas to separate titles, and orders the titles from most granular to least (confirm @mccalluc).

**Comment by mccalluc** [comment]
@afred: yeah, commas, and I can't actually remember what the order is right now, but since we're not sure which we really want, I'm not concerned about that.

**Comment by caseyedavis12** [comment]
@Afred @mccalluc: Sorry for being out of the loop on github these past few days. Getting ready to catch up now or at least review questions and gather necessary info to make a decision within the next few days.

#508 hasn't been finalized yet. Still on the list for final decision. Will let you know by tomorrow after 2pm.

**Comment by caseyedavis12** [comment]
Hi @afred and @mccalluc: We would prefer that in search results, the titles are concatenated from most general to most granular. We would like titles to be separated by semi-colons instead of commas. 

On a  Detailed Record Page, we would like the Title Header to display the most granular title, unless the title has an Episode Number. If it has an Episode Number, default to Episode Title.
