### ISSUE TITLE
Links back to organization page for playback.

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#536]
@sroosa @caseyedavis12 : This is doable; just need to pin down the details.
- Where will the URL be in the PBCore? Work something out with Kevin, and then when you've got one record updated, give me a record ID that demonstrates it.
- Let me know whether this is a bulk update Kevin with do, or if the last-updated in the AMS can be relied upon.
- What do you want this to look like in the UI? One proposal:
![screen shot 2015-07-24 at 2 49 45 pm](https://cloud.githubusercontent.com/assets/730388/8882282/bfd14d22-3213-11e5-94e6-2ee0c23d58d9.png)
- (Alternatively, maybe put the link in the grey box? All the "playable" stuff in one place.)
- If there is an outside link, is that enough to make this count as "digitized", ie these records would come back in the default search, once that's implemented?

(Lots of little bits here... Not a big job, but I'd like not to begin until the details are set. Thanks!)

**Comment by caseyedavis12** [comment]
Thanks, @mccalluc! @sroosa can provide the answers to your first two questions.


#3 & 4: I like your idea of putting the link in the grey box. The screenshot you provided would also suffice but it may be more noticeable in the playable area as you suggested.

#5: I would consider the material that is available elsewhere "Online Reading Room" material. We digitized it but we are providing access elsewhere online. I would lump this material into the ORR bucket. Since we digitized it as part of the project, it should have an "Audio" thumbnail, as opposed to "Audio - Not Digitized."

.

**Comment by mccalluc** [comment]
This issue is for the UI: getting the data into and out of the the AMS is #548.

**Comment by mccalluc** [comment]
Closing: We'll check that this works with real data when real data is provided as part of #548.
