### ISSUE TITLE
anchor-link or catalog/*.iframe

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#551]
@Muraszko / @foo4thought : I remember someone asking for an anchor link so that the pages could be loaded in a webkit object database with the player right at the top. Can you remind me who that was?

**Comment by foo4thought** [comment]
It was me who asked for a named anchor on the catalog view in aapb.


The desired behavior will be that links to the "page" that include the anchor will load to put the named anchor at the top of the browser view.  The current process forces the user to scroll to that point.


Thanks.




-- kevin carter
-- programmer analyst
-- wgbh educational foundation
-- 1 guest street
-- boston, ma, usa, 02135
-- 6173005923 v/vm/fax
-- www.wgbh.org

-- WGBH:  pioneering public education since 1951 with content and
technology to enlighten and enable.


________________________________
