### ISSUE TITLE
Test all access control combos

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#575]
@sroosa / @caseyedavis12 : Please confirm that this covers all the access control combos, and that this is the behavior you want:
```
       'link' = link to remote resource, plus thumbnail
       'player' = player rendered on page load
       'tos' = TOS click-through, and then a player
       'data' = just metadata, no player, no TOS, no apology.

                GBH      US     non-US	bot
     remote     link     link   link    link    
     public     player   tos    data    data
     protected  player   data   data    data
     private    data     data   data    data
     no media   data     data   data    data
```
(Special messages are defined in #577.)

**Comment by caseyedavis12** [comment]
@mccalluc: for Protected and Private, since these materials were digitized, we also want the audio-digitized or video screenshot thumbnail to appear at WGBH, US, and non-US, along with data.


For 'no media' we also want the thumbnail to appear (video - not digitized or audio - not digitized)

tagging @sroosa so that she can test this when the time comes

Let's talk about the note that appears to users when they cannot view media for a particular purpose.
________________________________

**Comment by mccalluc** [comment]
(Clarifying: "data" will include thumbnail. My sense is that only the moving images need to be handled specially.)
