### ISSUE TITLE
Make the browse-the-collection based on free-text searches

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#627]
interns will do the research, chuck will implement

**Comment by caseyedavis12** [comment]
@mccalluc and @sroosa: this looks done, although our Director at the Library Alan had two suggestions:

- change “War and Conflict” to “War” (since the search is for “war or battle,” conflicts that are not wars won’t come up);
- for “Race and Ethnicity,” add search terms for “segregation,” “desegregation,” “discrimination,” “African Americans,” “Negro,” “Black Power,” “NAACP,” “SNCC,” “Student Nonviolent Coordinating Committee,” “Congress on Racial Equality,” “National Urban League,” “Southern Christian Leadership Committee,” “SCLC,” “Black Muslims,” “Japanese Americans,” “Chinese Americans,” “Korean Americans,” “Asian Americans,” “Cuban Americans,” “Latinos,” “Hispanic,” “Chicanos,” “Irish Americans,” “Italian Americans,” “Jewish,” “German Americans,” “Polish Americans,” “Filipino Americans,” “Indians,” and “Native Americans.”

**Comment by mccalluc** [comment]
- I can shorten up "War", but some other term in the last column should be expanded, just so they all line up on the screen. "Theater" -> "Theater and Acting"
- I'll expand the "Race and Ethnicity" search, but I think we can leave of the "Americas"? I'll see what the results are like.
