### ISSUE TITLE
Accessibility: Did we get caption files from Crawford? Can they go on the media server?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#70]
@Muraszko : Some of the tapes sent to Crawford may have contained closed-captioned video -- and hopefully it's been extracted into a format suitable for use in a web player? Do you have a manifest of CC files to expect? Can you put them on the media server as you encounter them?

**Comment by caseyedavis12** [comment]
Crawford has provided the closed caption files; I don't have a manifest but have requested one from Lauren Sorensen who has received the files on her copy of the preservation file LTO tapes.

I need to receive permission from the Legal Counsel to put these on the media server and make them available on the website, and I have put in a request to the Counsel to review and determine.

Best,
Casey

**Comment by Muraszko** [comment]
@mccalluc  
I just checked a proxy file of a tape that was closed captioned and there were no captions on the file.
This could mean a few things.
1) The caption data was not saved as part of the preservation digitizing
2) Caption data was not retained when transcoding to mov (mp4)
3) Something else?

Doing a quick look at our MARS records, only 13 tapes from WGBH sent to Crawford for AA were cataloged as being closed captioned.  

<STRIKE>We should check with Casey to see if they did create caption files.</STRIKE>
Ha, there you go.

**Comment by mccalluc** [comment]
@Muraszko : Would the next step be to ask Crawford where the files are? I'd assume they'd be adjacent on the LTO, but conceivably they were segregated? No urgency, but if we are missing stuff better to start tracking it down sooner than later.

**Comment by caseyedavis12** [comment]
The files aren't missing. The files were only placed on the preservation LTO tapes, which is why we don't have them yet, as our copy of the preservation tapes is still in underground storage in Kansas. Lauren received her copy of the preservation LTO tapes last week, and I have asked her to deliver copies of the closed caption files to us.

Best,
Casey

**Comment by mccalluc** [comment]
Awesome! sorry for misunderstanding. Let's leave this open until we've seen them and they are being moved onto the media server in their own subdirectory. Thanks!

**Comment by caseyedavis12** [comment]
As a reminder, the closed caption files being available on the website are not required as part of the October deliverable; however, I asked Lauren if the Library could provide us with the closed caption files by July so that Chuck could have enough time to attach them to the proxies. Lauren said that the Library will not be able to provide us with closed caption files by that time. We may not be able to receive them until March 2016, when the Library finishes their ingestion of the preservation files. We will get our own copy of the preservation files, but it would be a lot of work and time to extract the closed caption files off of the approximately 965 LTO-5 tapes (formatted TAR). It's unfortunate but I say let's either close this issue or plan to keep it open until as late as March 2016.

**Comment by mccalluc** [comment]
Ok, closing this in favor of #444.
