### ISSUE TITLE
Further limiting searches with additional keywords

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#701]
Searching now, you cannot further limit searches using keywords after you have entered a search term either in the home page box or in the advanced search box. For example, if you enter “National Association of Educational Broadcasters” either in the home page box or in the “This exact word or phrase” box in the advanced search, you get 5,379 digitized records, but there is no easy way to further limit the search to the “Frank Lloyd Wright” programs within this material. If on the left side of the page we added “Keyword” as one of the ways to limit the search, that would help.

**Comment by mccalluc** [comment]
Actually, you can change your query up at the top, and it keeps the facets you've applied.

I'm reluctant to add a second search box somewhere else on the screen because then the user starts wondering what the difference is. (We accepted this on the homepage with some reluctance.)

I'm also reluctant to get into big UI changes at this phase in the project. Adding one thing at one place will shift others around.

I would like to close this, but I'll let the call be yours, @caseyedavis12.

**Comment by mccalluc** [comment]
@caseyedavis12 : can we close this?

**Comment by caseyedavis12** [comment]
@mccalluc: you can close
