### ISSUE TITLE
UI: Label IDs?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#73]
@sroosa : IDs are now displaying in the UI... but do they need labels? Actually, what's the user story around IDs? If we just provided a view of the raw pbcore (#57), would that be enough? The downside of displaying the sources is that they could be confusing: "http://americanarchiveinventory.org" as a label string won't make much sense to most people.

**Comment by sroosa** [comment]
I think it makes sense to label ids, if we display them. I know from experience on other projects that if we don't display the ids, then when we get emails from users about specific records then there will need to be a lot more manual work on our end. While I agree that it can be confusing, I also think the benefits outweigh the negatives. 
I would suggest labeling them, but perhaps having the "http://americanarchiveinventory.org" display as AAPB GUID, rather than as the string in the xml. I know it's a stupid extra layer, but it's the best solution I can think of.
