### ISSUE TITLE
Mississippi Public Broadcasting thumbnails not appearing

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#798]
http://americanarchive.org/catalog?f%5Borganization%5D%5B%5D=Mississippi+Public+Broadcasting+%28MS%29&f[access_types][]=digitized

**Comment by caseyedavis12** [comment]
MPB's records in the public website do not have an underscore in the URL. This was because their original AAPB GUID had a cpb-aacip- instead of cpb-aacip/. So the AAPB public website didn't change it to an underscore. 

In addition, MPB's records are not appearing in the AMS interface at all. This is definitely part of QA.

**Comment by mccalluc** [comment]
@caseyedavis12 : Is this something that will be cleaned up on the AMS, we'll reingest, and delete the old records, and be done... Or does AAPB ingest need to be able to handle the the AMS data as is? That would involve tweaking this bit:
```ruby
 def id
    @id ||= xpath('/*/pbcoreIdentifier[@source="http://americanarchiveinventory.org"]').tr('/_', '_/')
    # AAPB IDs, frustratingly, include slashes. We don't expect to see underscore,
    # so swap these two for a loss-less mapping. May revisit.
  end
```

I think either way could work.

**Comment by caseyedavis12** [comment]
@mccalluc: I would prefer that we handle the AMS data as is. The MPB GUIDs were automatically generated by the AMS, and now there are instantiations that rely on the GUID looking that way. I don't want to change the data in the AMS and risk cascading effects.


Thank you!


@foo4thought: any idea why the Mississippi Public Broadcasting records are not appearing at all in the AMS interface?

**Comment by foo4thought** [comment]
Annoying, isn't it?  I used the mysql emulator to query the assets_list (sphinx) and found none for some known MPB asset ids; the instantiations_list seemed to be fine.


I installed the list of 20K + asset ids into the php script that updates the index and set it ablaze.  It is running now.




-- kevin carter
-- programmer analyst
-- wgbh educational foundation
-- 1 guest street
-- boston, ma, usa, 02135
-- 6173005923 v/vm/fax
-- www.wgbh.org

-- WGBH:  pioneering public education since 1951 with content and
technology to enlighten and enable.


________________________________
