### ISSUE TITLE
Change default from "grid" to "list" view for search results, and Exhibit section pages

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#809]
Instead of grid view, we now prefer list view as default for all exhibits. 

**EDIT: Done when:**
  - index view of search results defaults to list view
  - exhibit section pages display exhibit items in a list view

**Comment by caseyedavis12** [comment]
@mccalluc and @afred: please do work on this yet. I need to confirm that Karen agrees with this change.

**Comment by caseyedavis12** [comment]
@mccalluc and @afred: please proceed with changing exhibit default from Grid View to List view as part of post launch QA.

**Comment by afred** [comment]
@caseyedavis12 since the "show all items" page for Exhibits is actually the same as a regular search results page, i want to be clear that you want all of the following:

  1. For regular search results, continue to default to grid view. Allow switching to list view.
  1. For "show all items" for Exhibits, change default view to list view. Allow switching to grid view.
  1. For [an Exhibit section page](http://americanarchive.org/exhibits/civil-rights/places) that show a subset of Exhibit items, continue to show grid view only.

**Comment by caseyedavis12** [comment]
@afred: Apologies for not being clear. We want all search results, including regular search results, "Show all in an exhibit" and exhibit sections to appear as List View by default. No parts of the website should default to Grid View


cc @mccalluc

**Comment by afred** [comment]
ok thanks for the clarification. Changing the ticket title to reflect.
