### ISSUE TITLE
Discussion: AMS strips out all text formatting

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#811]
If we code the formatting into descriptions in the AMS, will the public website display the formatting properly? For example, <em>around italics</em> and &#34; for quotation marks.

**Comment by mccalluc** [comment]
@caseyedavis12 :
- Let's distinguish between character entities (of which a [small number of cases](https://github.com/WGBH/AAPB2/blob/master/lib/html_scrubber.rb#L4) are handled) and text formatting (which we're not doing).
- There's a ton of bad formatting that's already out there that we're cleaning up at render time (#439): Distinguishing new markup we want from old broken stuff we want to clean is hard/impossible.
- Why? Do you think you need this for every field?
- Can you point at another analogous site that does support text formatting like this?
- This makes data exchanges more complicated: Instead of just containing text, now we're text + some formatting, and that information needs to be passed down the line. Unmaintainable.

**Comment by mccalluc** [comment]
@caseyedavis12 : If it wasn't obvious, I'd like to close this. If there is a particular need you have, let's talk, and maybe make a new more precise issue.

**Comment by caseyedavis12** [comment]
@mccalluc: here is an example: http://americanarchive.org/catalog/cpb-aacip_500-r785p02p


The last sentence in the description should have the title of Glenn Eskew's book italicized.

**Comment by mccalluc** [comment]
@caseyedavis12 : The more I think about this, the worse I feel about it. Grab me if you want more explanation.
