### ISSUE TITLE
Number of records per page

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#817]
From Alan: The options should be 15, 30, 60, 120.

**Comment by mccalluc** [comment]
@caseyedavis12 : No: In a narrow view it's just two across, so the default/smallest number needs to be a multiple of 2 and 3: 6 is too small and 18 is too large. We ended up where we are for a reason.

**Comment by caseyedavis12** [comment]
@mccalluc: Now that we removed the flexbox, the problem with the 10th record on the page appearing larger than all the others (in grid view) should no longer persist. If this is the case, can we switch it back to 10 records by default?

**Comment by mccalluc** [comment]
Ok to revert to original [10,20,50,100]? Whatever. @caseyedavis12 / @afred?

**Comment by caseyedavis12** [comment]
Yes, thanks @mccalluc

**Comment by afred** [comment]
@caseyedavis12 the 12-per-page was not because of the larger record.. it's because the results show in rows of 3. 12 is a multiple of 3, but 10 is not. So with 10-per-page, you'll end up a single record on the last row on every page of the grid view (with 20-per-page you'll have 2 on the last row, etc). Is that ok?

![image](https://cloud.githubusercontent.com/assets/1507490/11007518/69f8ed7e-8498-11e5-9900-628dcfcf2724.png)

**Comment by caseyedavis12** [comment]
@afred: with flexbox, the 10th record used to appear much larger than all the other records. I'm fine with the 10th record appearing on its own row now since that bug is now fixed.
