### ISSUE TITLE
Capitalization of titles

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#820]
From Alan: Capitalization of titles is not uniform. For example, the Pacifica titles are capitalized according to library rules (e.g., Asian American women vs. the women's movement), while others are not (e.g., Art and Violence).

Not sure if this can be done programmatically or if it needs to be done through manual cataloging.

**Comment by mccalluc** [comment]
We're doing a tiny bit of capitalization cleaning [in code](https://github.com/WGBH/AAPB2/blob/master/scripts/lib/cleaner.rb#L228), and more could be done, but it only happens on a case by case basis.

In terms of things that are worth human time, tweaking capitalization ranks way, way down there for me, but that's just my opinion.

@caseyedavis12 : Can you narrow this down to something actionable, or close?

**Comment by caseyedavis12** [comment]
@mccalluc: would it be difficult to implement capitalizing the first letter of every word in a title except for certain articles and other short words? I could give you a list of words to leave out. 

Reminder: please don't work on this yet until Karen and Nick confirm that you can work on this.

**Comment by caseyedavis12** [comment]
Please proceed.

**Comment by afred** [comment]
@caseyedavis12 as @mccalluc points out, if the title data is cased in a strange way, it's impossible to come up with rules that can guess correctly all the time, and in some cases, trying to be too clever will cause otherwise good titles to become oddly cased.

For one, we can't account for every acronym, so in some cases, we'd end up doing the wrong thing
  * "Hamers to be CEO of ING" would become "Hamers to be Ceo of Ing"
  * "WHO declares bacon deadly" would become "Who Declares Bacon Deadly"
  * "WILL will participate in AAPB" would become "Will Will Participate in Aapb"

But in other cases, some of the acronyms we do recognize may not be intended to be acronyms.
  * "DELIVER US FROM EVIL" would become "Deliver US From Evil" because we recognize "US" as acronym for United States. But, if we stopped recognizing "US" then...
  * "Terrorists Target US" would become "Terrorists Target Us".

It's very hard to say whether our rules would actually result in more correctness.

I suggest we do the following:
  * If the title is ALL CAPS _and_ more than 1 word, then go ahead and title case it, because even if it's incorrectly title-cased, it will look better than all caps.
  * Otherwise, use title as-is, because we just don't know if we'd be doing good or ill.

(NOTE: this is prime example of what we means when we say "we're playing whack-a-mole")
![image](http://i.imgur.com/moo0BtB.gif)

**Comment by mccalluc** [comment]
(Sorry: Had to delete the cat: I was paralyzed by the cuteness.) For a way forward, I'd suggest
- No change to the existing code, which tries to guess capitalization *only* if all caps or all lower.
- We can run a report for you that identifies all examples where auto-capitalization makes a change, and you can take it from there. ... but only if you'd use it? @caseyedavis12

**Comment by caseyedavis12** [comment]
Let's close and consider this as part of the cataloging work that needs to be done by @sroosa's interns
