### ISSUE TITLE
How to handle /catalog with no parameters?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#83]
_home_text.htm.erb defines content for /catalog when there are no paramaters. Do we have a need for it? Should it redirect to a default search? Mike doesn't have an account yet, but I'll get him to weigh in.

**Comment by Hammicakes** [comment]
Using Digital Commonwealth as an example they have both a basic and an advanced search page.

I don't think we need a basic search page but an advanced search page would be useful.

**Comment by caseyedavis12** [comment]
Hi Mike,

We are only going to be able to provide a basic search for the April (Initial) Website, but we are hoping to have an advanced search page for the October (Final) Website. The basic search page would allow for a general keyword search across all fields and searching within fields like title, date, and people. A future advanced search page would allow for boolean searching across all fields and within fields using AND, OR and NOT.

I still think that a basic search page would be good so that we can build upon it for the October deliverable.

Thoughts Drew and Chuck?

**Comment by Hammicakes** [comment]
Totally works for me.

**Comment by mccalluc** [comment]
done:
```ruby
    actual_params = params.keys - ['action', 'controller']
    if !actual_params.empty? &&
       params.except('action', 'controller', 'utf8', 'search_field')
            .select { |key,value| !value.empty? }.empty?
      redirect_to '/catalog'
```
