### ISSUE TITLE
Exhibits list view: Title Appears Twice

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#831]
In Alan's exhibit, we need to include the Title and the URL in each section because he has organized his exhibit in bullet lists. Please see: http://americanarchive.org/exhibits/civil-rights/places

But when one clicks "show all items in this exhibit," the title that we added in the section markdown is added to the search results in the list view. We would like for this to not be shown in the list view.
![screen shot 2015-11-05 at 12 25 26 pm](https://cloud.githubusercontent.com/assets/5992135/10976228/ae5644ca-83b8-11e5-81e3-11248a9f3ab5.png)

**Comment by mccalluc** [comment]
@caseyedavis12 : Can we get rid of that bit across the board? It was [introduced](https://github.com/WGBH/AAPB2/pull/525/files#diff-03c3800a9a92e0e94a17c4d4af464761R19) to give a little more info on search results, but since then it looks like you have been aggressively cataloging, so it's unlikely that useful info will only be there?

**Comment by mccalluc** [comment]
Agreed that we can get rid of this across the board.
